<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.2 setup script
 * Date: Mon, 16 Jul 2018 04:59:53 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: master [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'master';
$cfg['Servers'][$i]['host'] = 'master.cbr6mhuodbur.ap-northeast-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'c:0RO_u|1F#W*A>wjP,eeDjuP(pMpCp%';
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>